
#Env non-specific properties go here
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

info:
  app:
    name: @project.name@
    version: @project.version@


server:
  port: 8080

spring:
  application:
    name: @project.name@
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false #Supress warning message: "Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException"

